#
###################################
# Site wide configuration
####################################
#
title: eirvandelden.com
email: eirvandelden.com
description: My random ramblings about developing, Dungeons & Dragons and life.
# the base hostname & protocol for your site
# If your project is placed in https://github.com/yourname/yourname.github.io at master branch
# Then, the 'url' is: http://yourname.github.io
# If your project is placed in another repository as a gh-pages branch, like: https://github.com/yourname/projectname
# Then, the 'url' is: http://yourname.github.io/projectname
url:

#
###################################
# Jekyll configuration
####################################
#
markdown:    kramdown
highlighter:  pygments
excerpt_separator: <!--more-->

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Etienne van Delden
  avatar: etienne.png
  job: "Developer. Dungeon Master."
  bio: "All my ramblings I care to share with the world."
  email: eirvandelden@me.com
  disqus-shortname: eirvandelden
  twitter: eirvandelden
  facebook: eirvandelden
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: eirvandelden
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
